### ISSUE TITLE
'when' XPath expressions in 'uses' not being correctly validated

### ISSUE THREAD

**Issue by paulo-g** [mbj4668/pyang#495]
For the example:
```
module test {
    namespace "https://example.com";
    prefix test;

    grouping g1 {
        leaf l1 { type int8;  }
        uses g2 {
            when "l1 > 0";
        }
    }

    grouping g2 {
        leaf l2 { type int8; }
    }

    uses g1;

}
```
I get the following warning when validating using pyang 2.0.1:
`test.yang:16 (at test.yang:8): warning: node "test::l1" is not found in "test::l2"`
However, the model itself should be valid, no warning should exist.

I've done some debugging, and it seems that the 'when' expression of the 'uses' is inherited by the leaf within the grouping as is, but in reality the context for the when expression is the parent of l2, not l2 itself.

If the implementation approach is to move the 'when' expression from the 'uses' to all statements within the used grouping, then the xpath evaluation needs to have the statement parent as context, not the context itself. 
It would probably be enough to provide the When statement with a base context that would be used instead of the When parent.

Apparently this only happens for this nested grouping scenario, which is also something that doesn't make that much sense.
Thanks!

**Comment by aashaikh** [comment]
has this bug been resolved? (I'm still seeing it in the 2.1 release).  Am also running into it with some OpenConfig modules where the context node seems to be incorrectly identified by pyang as the node being instantiated by the `uses` statement rather than its parent node.  This results in node not found errors.

For comparision, confdc (7.2.0.1) does not produce the same errors for this case.

**Comment by mbj4668** [comment]
No it hasn't been fixed yet. I'll try to have a look later this week.

**Comment by aashaikh** [comment]
thank you -- we use pyang as our primary validation tool in OpenConfig CI

**Comment by mbj4668** [comment]
@aashaikh I have fixed this, but it would be great if you could verify that it fixes the problem in your modules as well.

**Comment by aashaikh** [comment]
thanks -- will check and update here.  On a first run through, I do see some new errors being flagged in addition to those I expected so will need to dig into what's going on there.

**Comment by mbj4668** [comment]
Hi,

Yes, I just realized a moment ago that the fix was not quite correct.  I am
looking into this.  I'll let you know when I'm done, and meanwhile you
don't have to run any more tests.  Sorry about this.


/martin

**Comment by mbj4668** [comment]
@aashaikh I think I have fixed this now.  Please run your tests and let me know the result.

**Comment by aashaikh** [comment]
I was able to confirm that the errors cited in the current version are correctly identified, at least for the OpenConfig modules -- so I'd say this LGTM.  Thanks very much for the quick fix and followups.

**Comment by aashaikh** [comment]
Are there any near-term plans to issue a pyang release that includes this fix ?

**Comment by apoorvashastry** [comment]
@paulo-g I am still seeing this issue even after your fix.

Below is the scenario

module test {
    namespace "https://example.com";
    prefix test;
    
    list l1 {
      key k1;
      leaf k1 {
         type uint32;
      }
      uses grouping g1;
      leaf leaf1 {
         type uint32;
      }
      uses grouping g2 {
        when "(count(leaf1) = 1) or (count(leaf2) = 1)";
      }
   grouping g1 {
       leaf leaf2 {
          type uint 32;
       }
   }
}

Pyang is throwing error saying that it could not find nodes leaf1 and leaf2. Does this scenario covered with your fix??

**Comment by fredgan** [comment]
Hi, @apoorvashastry 
There are some grammar errors in your module.

Then I try to fix it, But I didn't catch any error pyang throwed.
